Update build infrastructure and packages to align with upstream pi-gen
Agent-Logs-Url: https://github.com/BlokasLabs/patchbox-os-gen/sessions/4a273872-95eb-4c12-9b0e-74515af4c937

Co-authored-by: gtrainavicius <477278+gtrainavicius@users.noreply.github.com>

diff --git a/scripts/common b/scripts/common
--- a/scripts/common
+++ b/scripts/common
@@ -12,7 +12,7 @@ bootstrap(){
 	BOOTSTRAP_ARGS+=(--arch armhf)
 	BOOTSTRAP_ARGS+=(--components "main,contrib,non-free")
 	BOOTSTRAP_ARGS+=(--keyring "${STAGE_DIR}/files/raspberrypi.gpg")
-	BOOTSTRAP_ARGS+=(--exclude=info)
+	BOOTSTRAP_ARGS+=(--exclude=info,ifupdown)
 	BOOTSTRAP_ARGS+=(--include=ca-certificates)
 	BOOTSTRAP_ARGS+=("$@")
 	printf -v BOOTSTRAP_STR '%q ' "${BOOTSTRAP_ARGS[@]}"
@@ -24,6 +24,9 @@ bootstrap(){
 		log "bootstrap failed: please check ${STAGE_WORK_DIR}/debootstrap.log"
 		return 1
 	fi
+
+	# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1050719
+	rm -f wget-log*
 }
 export -f bootstrap
 
@@ -44,20 +47,26 @@ unmount(){
 		DIR=$1
 	fi
 
-	while mount | grep -q "$DIR"; do
-		local LOCS
-		LOCS=$(mount | grep "$DIR" | cut -f 3 -d ' ' | sort -r)
-		for loc in $LOCS; do
-			umount "$loc"
-		done
+	for i in {1..6}; do
+		if awk "\$2 ~ /^${DIR//\//\\/}/ {print \$2}" /etc/mtab | sort -r | xargs -r umount; then
+			break
+		elif [ "$i" -eq 6 ]; then
+			log "Failed to unmount ${DIR}. Do not try to delete this directory while it contains mountpoints!"
+			return 1
+		fi
+		log "Retrying ($i/5)..."
+		sleep 1
 	done
 }
 export -f unmount
 
 unmount_image(){
-	sync
-	sleep 1
-	LOOP_DEVICE=$(losetup --list | grep "$1" | cut -f1 -d' ')
+	if command -v udevadm >/dev/null 2>&1; then
+		udevadm settle 10
+	else
+		sleep 1
+	fi
+	LOOP_DEVICE=$(losetup -n -O NAME -j "$1")
 	if [ -n "$LOOP_DEVICE" ]; then
 		for part in "$LOOP_DEVICE"p*; do
 			if DIR=$(findmnt -n -o target -S "$part"); then
@@ -110,3 +119,19 @@ ensure_next_loopdev() {
 	[[ -b "$loopdev" ]] || mknod "$loopdev" b 7 "$loopmaj"
 }
 export -f ensure_next_loopdev
+
+ensure_loopdev_partitions() {
+	local line
+	local partition
+	local majmin
+	lsblk -r -n -o "NAME,MAJ:MIN" "$1" | grep -v "^${1#/dev/} " | while read -r line; do
+		partition="${line%% *}"
+		majmin="${line#* }"
+		if [ ! -b "/dev/$partition" ]; then
+			mknod "/dev/$partition" b "${majmin%:*}" "${majmin#*:}"
+		fi
+	done
+	command -v udevadm >/dev/null 2>&1 || return 0
+	udevadm settle 10
+}
+export -f ensure_loopdev_partitions
